controller:
  config:
    main-snippet: "load_module /modules_mount/ngx_http_datadog_module.so;"
  opentelemetry:
    enabled: false
  extraModules:
    - name: nginx-datadog
      image:
        registry: docker.io
        image: datadog/ingress-nginx-injection
        # The first part of the tag, 'v1.14.1', is the version of the ingress-nginx controller.
        # The second part of the tag, '-dd.v1.11.0', which is optional, is the version of the
        # Datadog Nginx module.
        # Check <https://hub.docker.com/repository/docker/datadog/ingress-nginx-injection/tags>
        # for the list of all versions supported.
        tag: "v1.14.1-dd.v1.11.0"
        distroless: false
  extraEnvs:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    # add this env var to enable the App and API Security product
    - name: DD_APPSEC_ENABLED
      value: true