name: System Tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '00 03 * * 2-6'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
      NGINX_VERSION: 1.28.1
      WAF: ON
    steps:
      - name: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: git submodule sync && git submodule update --init --recursive
      - name: Login to Docker Hub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        run: 'make build-musl'
        env:
          BUILD_TYPE: RelWithDebInfo
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: binaries
          path: .musl-build/ngx_http_datadog_module.so

  main:
    needs:
    - build
    uses:  DataDog/system-tests/.github/workflows/system-tests.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      library: cpp_nginx
      binaries_artifact: binaries
      desired_execution_time: 600  # 10 minutes
      scenarios_groups: appsec
      scenarios: DEFAULT
      excluded_scenarios: INTEGRATIONS  # no test activated, and long warm-up
      skip_empty_scenarios: true

  # Ensure the main job is run to completion
  check:
    name: Check system tests success
    runs-on: ubuntu-latest
    needs:
    - main
    steps:
    - run: exit 0
